mass: 0.032        # Wheel mass in Kg
radius: 0.032    # Wheel radius in m
length: 0.025     # Wheel length in m, considering is as a cylinder
mesh: '../components/wheel.stl'  # Leave it empty ('') to have a red wheel
scale: ''
x_offset: -0.0
y_offset: 0.014
z_offset: -0.0
